# Generated by Django 5.0.4 on 2024-05-11 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_user_password_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineInfo',
            fields=[
                ('Vaccine_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Vaccine_name', models.CharField(max_length=100)),
                ('Vaccine_dose', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserVaccineDetails',
            fields=[
                ('UserVaccineDetails_id', models.AutoField(primary_key=True, serialize=False)),
                ('Vaccine_given_date', models.DateField(auto_now_add=True)),
                ('Vaccinator_id', models.IntegerField()),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Vaccine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.vaccineinfo')),
            ],
        ),
    ]
