# Generated by Django 5.0.4 on 2024-05-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_encryption_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryption_key',
            name='id',
        ),
        migrations.AlterField(
            model_name='encryption_key',
            name='userId',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
