# Generated by Django 5.0.4 on 2024-05-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_encryption_key_id_alter_encryption_key_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryption_key',
            name='encryption_key',
            field=models.BinaryField(),
        ),
    ]
