# Generated by Django 5.0.4 on 2024-05-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_encryption_key_encryption_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryption_key',
            name='encryption_key',
            field=models.CharField(max_length=64),
        ),
    ]
