# Generated by Django 5.0.4 on 2024-05-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_rename_encryption_key_encryptionkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservaccinedetails',
            name='Vaccinator_id',
            field=models.CharField(max_length=50),
        ),
    ]
